version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    container_name: rentacar-frontend
    networks:
      - rentacar-network

  bff-service:
    build: ./bff-service
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
    container_name: rentacar-bff
    networks:
      - rentacar-network
    depends_on:
      - azurite

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    container_name: rentacar-azurite
    networks:
      - rentacar-network

networks:
  rentacar-network:
    driver: bridge
